version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app:delegated  # Mount source code but avoid overwriting node_modules
      - /usr/src/app/node_modules        # Exclude node_modules from the host
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/usr/src/app:delegated  # Mount source code but avoid overwriting node_modules
      - /usr/src/app/node_modules          # Exclude node_modules from the host
